# Generated by Django 2.2.24 on 2021-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('CUI', models.CharField(max_length=13)),
                ('born_date', models.DateField()),
                ('Genre', models.CharField(max_length=9)),
            ],
        ),
    ]
