# Generated by Django 3.2.6 on 2021-11-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('CUI', models.CharField(max_length=17)),
                ('FechaNac', models.DateField()),
                ('Genre', models.CharField(max_length=10)),
                ('Codigo_tecnico', models.CharField(max_length=20)),
            ],
        ),
    ]
