# Generated by Django 3.2.9 on 2021-11-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coope', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
