# Generated by Django 2.2.24 on 2021-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('CUI', models.CharField(max_length=17)),
                ('FechaNac', models.DateField()),
                ('Genre', models.CharField(max_length=10)),
                ('User', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Puesto', models.CharField(max_length=60)),
                ('Estado', models.CharField(max_length=60)),
            ],
        ),
    ]
