# Generated by Django 3.2.9 on 2021-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coope', '0002_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('CUI', models.CharField(max_length=17)),
                ('FechaN', models.DateField()),
                ('Genero', models.CharField(max_length=10)),
                ('CodigoInsp', models.CharField(max_length=20)),
            ],
        ),
    ]
