# Generated by Django 3.2.9 on 2021-11-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coope', '0002_delete_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Afiliacion_date', models.DateField()),
                ('Genre', models.CharField(max_length=9)),
                ('Codigo_Socio', models.CharField(max_length=100)),
            ],
        ),
    ]
